[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.7"
tokio = { version = "1", features = ["full"] }
hyper = "1.5.0"
serde = { version = "1.0", features = ["derive"] }
tower = "0.5.1"
rcgen = "0.9"